<?php

namespace Cocorico\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserFacebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFacebookRepository extends EntityRepository
{
}
