imports:
    - { resource: admin.yml }

services:
    #Entities manager
    cocorico_cms.footer.manager:
        class: Cocorico\CMSBundle\Model\Manager\FooterManager
        arguments:
            - "@doctrine.orm.entity_manager"
        public: true

    cocorico.sitemap:
        class: Cocorico\CMSBundle\Sitemap\Sitemap
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@cache.app"
            - "@router"
            - "@liip_imagine.cache.manager"
        public: true